### PR TITLE
Update

### PR DESCRIPTION
**Pull request by bbhtt**
Building gst-plugin-bad from a release tarball fails due to some missing some gstreamer dependencies, so I switched it to git (uses the new monorepo now), I'll see if I can figure out that issue. Hopefully this'll work for now. 

I switched playitslowly to git since it allows to drop two patches here that were merged. All the other patches were from https://github.com/jwagner/playitslowly/pull/24, I squashed those to create a single patchfile since all of them patch the appdata.
The project readme says it is unmaintained so there won't be any new releases probably 

The other patch is from https://github.com/jwagner/playitslowly/pull/29

Ping @bochecha, please review, thanks!

Hey, @bilelmoussaoui, since you commited last, can you please review this one as well? Thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
> Build [101779 successful](https://buildbot.flathub.org/#/builders/32/builds/101779)

Getting:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.9/site-packages/playitslowly/app.py", line 535, in <module>
    main()
  File "/app/lib/python3.9/site-packages/playitslowly/app.py", line 524, in main
    win = MainWindow(sink, config)
  File "/app/lib/python3.9/site-packages/playitslowly/app.py", line 110, in __init__
    self.pipeline = Pipeline(sink)
  File "/app/lib/python3.9/site-packages/playitslowly/pipeline.py", line 53, in __init__
    self.audiosink = Gst.parse_launch(sink)
gi.repository.GLib.GError: gst_parse_error: no element "autoaudiosink" (1)
```
I think it needs -good as well.

**Comment by bbhtt** [comment]
> Build [101780 successful](https://buildbot.flathub.org/#/builders/32/builds/101780) 

Seems to work now

Also the app can export the audio files, so it needs rw access to at least one folder, I think I should add that.

**Comment by bilelmoussaoui** [comment]
thanks

**Comment by mbridon** [comment]
Apologies for not giving any sign of life and nota giving any reply 😢 

Thank you Bilal for stepping in 👍

I just reviewed the patches (better late than never I guess) and I agree with each of them, you did a great job here. 👍 

Would you like to be a commaintainer of this build ? 🤔

**Comment by bbhtt** [comment]
> Apologies for not giving any sign of life and not giving any reply

No worries :)

> Would you like to be a co-maintainer of this build ?

Thank you for the offer but I don't want to commit to maintaining it since I'm not sure if I'll have time and I don't use the app regularly. I can send in the occasional patches and runtime bumps if required though. Feel free to ping me on this. Thanks!

**Comment by mbridon** [comment]
Alright, thank you then 😃

**Pull request merged**
